/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#68000d",
        "on-error": "#690005",
        "primary": "#ffffff",
        "surface-container-lowest": "#0b0e15",
        "surface-container-highest": "#32353c",
        "secondary-container": "#00e3fd",
        "surface-container": "#1d2027",
        "surface-variant": "#32353c",
        "primary-container": "#fde400",
        "tertiary-fixed": "#ffdad7",
        "outline": "#979177",
        "inverse-on-surface": "#2d3038",
        "secondary-fixed": "#9cf0ff",
        "on-surface-variant": "#cdc7aa",
        "surface-tint": "#dec800",
        "on-primary": "#373100",
        "tertiary": "#ffffff",
        "on-tertiary-container": "#bd2c32",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#ffb3af",
        "on-secondary-container": "#00616d",
        "on-secondary-fixed-variant": "#004f58",
        "primary-fixed": "#fde400",
        "inverse-surface": "#e0e2ec",
        "surface": "#10131a",
        "on-tertiary-fixed": "#410005",
        "tertiary-container": "#ffdad7",
        "on-primary-fixed": "#201c00",
        "on-surface": "#e0e2ec",
        "on-background": "#e0e2ec",
        "on-error-container": "#ffdad6",
        "surface-bright": "#363941",
        "secondary-fixed-dim": "#00daf3",
        "outline-variant": "#4b4731",
        "surface-container-high": "#272a31",
        "background": "#10131a",
        "surface-dim": "#10131a",
        "inverse-primary": "#6a5f00",
        "on-secondary": "#00363d",
        "primary-fixed-dim": "#dec800",
        "surface-container-low": "#191c23",
        "on-tertiary-fixed-variant": "#920418",
        "on-secondary-fixed": "#001f24",
        "on-primary-fixed-variant": "#504700",
        "error-container": "#93000a",
        "on-primary-container": "#716500",
        "secondary": "#bdf4ff",
        "success": "#00f5a0",
        "canary": "#ffe600",
        "cyan": "#00e5ff",
        "coral": "#ff5c5c",
        "mint": "#00f5a0",
        "chalk": "#f4f6fa",
        "steel": "#8c96a8",
        "void": "#0c0e12",
        "carbon": "#12151c",
        "raised": "#181c26",
        "divider": "#282e3d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        "code-stream": ["JetBrains Mono", "monospace"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-lg": ["JetBrains Mono", "monospace"],
        "body-md": ["JetBrains Mono", "monospace"],
        "body-sm": ["JetBrains Mono", "monospace"],
        mono: ["JetBrains Mono", "monospace"],
        sans: ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [],
};
